[package]
name = "sp-generator-api"
version = "0.0.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sp-core = { path = "../core/" }

[features]
nightly = ["sp-core/nightly"]
