[package]
name = "sp-core"
version = "0.0.0"
authors = ["Danny McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
edition = "2018"

[dependencies]
# heapless = "0.7.1"
# displaydoc = "0.2.1"
indexmap = { git = "https://github.com/cosmicexplorer/indexmap", rev = "afe48b586baa6a310bc069ec448ebc4b0fdc6210" }
priority-queue = { git = "https://github.com/cosmicexplorer/priority-queue", rev = "dcb45d94e0295fc4a9c279cc130494375bb092f8" }
twox-hash = "1.6.0"
